# Se crea cada servidor de configuración, para lo que por cada servidor de
# configuración se abre una instancia de mongod en un puerto con la opción --port,
# se indica el directorio dónde se almacena los datos con la opción –dbpath,
# y se indica la opción --configsvr

# Instancia mongod para el servidor
mongod --dbpath C:\data\config1 --configsvr --port 27022  --replSet replica1
mongod --dbpath C:\data\config2 --configsvr --port 27023 --replSet replica1
mongod --dbpath C:\data\config3 --configsvr --port 27024 --replSet replica1

#A continuación, inicie los fragmentos como se muestra aquí.

mongod --dbpath C:\data\shard1\data1 --configsvr --replSet replica1 --port 27022
mongod --dbpath C:\data\shard1\data2 --configsvr --replSet replica1 --port 27022
mongod --dbpath C:\data\shard1\data3 --configsvr --replSet replica1 --port 27022

# Ahora, conéctese a uno de los servidores de fragmentos para habilitar un conjunto 
# de réplicas como mostrado aquí y en 

mongo hostname:26017

# Enrutadores

# Para crear un enrutador se abre una instancia de mongos 
# Este programa se puede encontrar en el directorio bin de la instalación de MongoDB.
# Se invoca indicando el puerto donde se va a ejecutar con la opción --port, se listan los
# servidores de configuración indicando el nombre del equipo y el puerto donde se ejecutan,
# y se usa la opción --configdb para indicar que es un enrutador.

mongos --configdb localhost:27022,localhost:27023,localhost:27024  --port 27021
mongos --configdb replica1/localhost:27022,localhost:27023,localhost:27024  --port 27021

# Hay que observar que también es posible en este paso indicar
# el tamaño de los trozos con la opción --chunkSize. Si no se indica esta opción,
# por defecto toma el valor de 64 MB.

# Shards
#  Se van a crear, por ejemplo, dos shards, por lo que es necesa- rio disponer de dos
#  directorios para cada uno de los servidores

# Para crear un shard se abre una instancia de mongod indi- cando
#  el puerto donde se va a ejecutar con la opción –port, se indica
#  el directorio donde se almacenan los datos con la opción –dbpath,
#   y se indica la opción --shardsvr
mongod --dbpath C:\data\shards\n1 --shardsvr --replSet replica1 --port 27026
mongod --dbpath C:\data\shards\n2 --shardsvr --replSet replica1 --port 27027
mongod --dbpath C:\data\shards\n3 --shardsvr --replSet replica1 --port 27028


# A continuación se agregan los shards al clúster (figura 160). Para ello se inicia una instancia de mongo
#  en el puerto donde se está ejecutando el enrutador, y cada shard se añade con el comando sh.addShard 
#  («Nombre del equipo: puerto»), indicando el equipo y el puerto donde se ejecuta el shard.
sh.addShard(«Nombre del equipo: puerto»)
sh.addShard("replica1/localhost:27026")
sh.status()

# Ahora, para habilitar la fragmentación para una base de datos, use este comando.
mongos> sh.enableSharding("demos")
# Para habilitar la fragmentación de una colección, use este código.
mongos> sh.shardCollection("demos.users",{"id":1}

{
        "ok" : 0,
        "errmsg" : "no such command: 'addShard'",
        "code" : 59,
        "codeName" : "CommandNotFound",
        "lastCommittedOpTime" : Timestamp(1650504898, 1),
        "$clusterTime" : {
                "clusterTime" : Timestamp(1650504898, 1),
                "signature" : {
                        "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
                        "keyId" : NumberLong(0)
                }
        },
        "operationTime" : Timestamp(1650504898, 1)
}